image: python:3.10

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install -r requirements.txt || pip install pytest

test:
  script:
    - pytest